import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { readFileSync, writeFileSync } from "fs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	// Aggregate plugin CSS into the distribution stylesheet:
	// import order defines the cascade, so keep it authoritative.
	// pickr-nano comes last so the picker theme bases on top of the
	// plugin's own overrides, matching the previous bundle order.
	const cssFiles = ["pickerOverrides", "settings", "beautify", "pickr-nano"];
	const css = cssFiles
		.map((name) => readFileSync(`src/css/${name}.css`, "utf8"))
		.join("\n");
	writeFileSync("styles.css", css);
	process.exit(0);
} else {
	await context.watch();
}
